<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AMGH.ITInventory.Application\AMGH.ITInventory.Application.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.Persistence\AMGH.ITInventory.Persistence.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.Infrastructure\AMGH.ITInventory.Infrastructure.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.Security\AMGH.ITInventory.Security.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.Reporting\AMGH.ITInventory.Reporting.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.QRCode\AMGH.ITInventory.QRCode.csproj" />
    <ProjectReference Include="..\AMGH.ITInventory.Shared\AMGH.ITInventory.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
